### ISSUE TITLE
OriginVsSender test seems not working

### ISSUE THREAD

**Issue by 0xArDANT** [RareSkills/Solidity-Exercises#27]
It seems like the testSetNumber isn't working.

I found that we need to add a line to prank the tx.origin and msg.sender with the same address using the prank function with 2 parameters :
https://book.getfoundry.sh/cheatcodes/prank

    function testSetNumber() external {
        address OxArDANT = vm.addr(1);
        vm.prank(OxArDANT, OxArDANT);
        originVsSender.setNumber(42);
        assertEq(originVsSender.number(), 42, "expected number to be 42");
    }

**Comment by tanim0la** [comment]
addressed

**Comment by 0xArDANT** [comment]
Thank you very much Ser
