### ISSUE TITLE
Donations does not test for multiple amountsDonated

### ISSUE THREAD

**Issue by cryptanu** [RareSkills/Solidity-Exercises#8]
The test in Donations.t.sol does not account for multiple donations as stated in the Donations.sol file. 
This could allow a reset of the amountDonated mapping via assignment (=) instead of an increment (using +=).
i.e.
        `amountDonated[msg.sender] = msg.value;    // runs and re-assigns the mapping on every run`
instead of 
        `amountDonated[msg.sender] += msg.value;  // to increment the mapping per address`

Consider including the extra check in the tests.

**Comment by tanim0la** [comment]
addressed
